---
title: " "
output: pdf_document
---

# Discussion

In this study, we delved into the analysis of waterbird count data using a state-space time series framework, a novel approach that models the waterbird counts by separating the observation and state error of the waterbird populations. By harnessing this methodology, we aimed to derive insights into the population dynamics of waterbirds while simultaneously assessing their ecological diversity through the calculation of three key diversity indices: the Living Planet Index (LPI), Shannon index, and Simpson index. Through the utilization of Markov Chain Monte Carlo (MCMC) sampling techniques, we not only obtained insight into the temporal trends of waterbird populations, but also quantified the multifaceted aspects of their ecological diversity. This section elaborates on the results derived from our analysis, discussing the implications of the state-space time series model and the calculated diversity indices.

The SSM output covers both the summer and winter populations of waterbird at Barberspan. In figure (x) we see that the summer population of waterbirds seem to be increasing over time while winter populations are fairly steady with some random fluctuations.

According to the LPI output we notice that the change in waterbird populations each year at Barberspan is staying fairly constant, with random fluctuations for both summer and winter. The overall waterbird population appears stable, however there are studies that show decreasing trends of migratory waterbirds in wetlands in Southern Africa. 

A study on migratory waterbirds in South Africa reported that 11 of the 16 palearctic migrants investigated experienced negative trends from 2005-2009 [@barshepIdentifyingEcologicalLifehistory2017]. Another paper analysing palearctic migrants in Sandwich Harbour and Walvis Bay, Namibia, reported similar findings; four of the 12 palearctic migrants studied experienced declines while only one species experienced an increasing trend (Common Whimbrel) from 1990-2013 [@simmonsDeclinesMigrantShorebird2015]. Further studies show that Palearctic-Afrotropical migratory waterbirds are experiencing declines in abundance globally [@kirbyKeyConservationIssues2008; @deniauFlywaysHellEmpirical2022].

The diversity indices in Barberspan paint a different picture compared to the population abundance. While waterbird population abundance remains fairly stable over time, waterbird diveristy seems to decrease. This is shown in figure (x) as we see a decrease in evenness over time (illustrated by the Simpson's index) and a decrease in the effective number of waterbird species over time (illustrated by the exponentiated Shannon's index). figure (bar plot) shows us the potential cause for these numbers as the Egyptian Goose and the Red-Knobbed Coot made up 70% of all waterbird counts at Barberspan with the Red-Knobbed Coot being most dominant making up 58% of all counts.

These displays of unevenness coincides with other studies of wetland waterbirds in Southern Africa. A study conducted in a South African riverine habitat, the Shamvura stretch of the Okavango River, also found high levels of dominance among the waterbirds present in the wetland [@kopijSeasonalChangesDiversity2018]. In this study there were 6 resident waterbirds out of the 84 recorded waterbirds that were classified as dominant: African reed cormorant, African openbill, cattle egret, wattled lapwing, African darter and white-faced duck.

Aside from the data output, it is also necessary to mention the effectiveness of the state-space model and why it was used over other, more traditional methods. SSMs separate the observation error from the latent error such that researchers are able to differentiate between biological variation and imprecise sampling methodologies. This generally allows for better estimates of ecological qualities compared to more traditional approaches that model all the random variation into one term [@campEvaluatingAbundanceTrends2016].

SSms are able to give more biological insight into the change in abundance over time. For example, SSMs were compared to ANOVA methods and it was found that the ssm model resulted in much higher statistical power than any of the ANOVA methods used in the study [@devalpineBetterInferencesPopulationDynamics2003].

Future work is to be done on this topic. This method of calculating diversity indices can be used on counts for other animals and tested according to more traditional approaches to discover what truly performs best. Further work could go into the current model to incorporate covariates into the model to identify drivers for population change and increase the accuracy of the calculated diversity indices.


