---
title: " "
output: pdf_document
---

# Introduction

<!-- Biodiversity (or biological diversity) is, in its simple terms, refers to the "variety of life" [@gastonBiodiversityIntroduction2013]. According to the Convention on Biological Diversity, "Biological diversity means the variability among living organisms from all sources including, inter alia, terrestrial, marine and other aquatic ecosystems and the ecological complexes of which they are part; this includes diversity within species, between species and ecosystems." -->

<!-- Biodiversity is an essential characteristic for ecosystem health, as loss of biodiversity leads to reduced ecosystem resilience [@ritchieBiodiversity2021]. Every species in an ecosystem plays a role in its upkeep, and a great loss to any group of these species is cause for alarm [@duffyWhyBiodiversityImportant2009]. Unfortunately, it has been widely reported that there has been a decreasing trend of global biodiversity. According to WWF’s 2018 living planet report, there has been a 60% global decrease in biodiversity of mammals, fish, birds, reptiles and amphibians [@grootenLivingPlanetReport2018].  -->

<!-- Given the importance of biodiversity there have been many efforts in preserving biodiveristy on local and global levels. The most notable of these campaigns is the Aichi Biodiversity targets. The Aichi Convention on Biological Diversity presented a strategic plan in 2011 to improve global biodiversity. This plan is made up of 5 goals and 20 targets. The strategic plan needed appropriate metrics to measure its success, and as a result the Living Planet Index (LPI) was created. The LPI measures the progress of Aichi strategic goal C. Aichi strategic goal C states: “To improve the status of biodiversity by safeguarding ecosystems, species and genetic diversity” (Convention on Biological Diversity 2020). -->

With the ongoing concern about biodiversity loss, monitoring biodiversity at various levels of biological organisation is important [@pereira2013essential]. At the organismal level, biodiversity is generally measured by three components: number of species, total number of individuals (abundance), and how the individuals are distributed across species (evenness). We lose biodiversity if abundance decreases, if species go extinct, if communities become dominated by a few common species, or a combination of these processes. To measure changes in biodiversity, we need indicators that are sensitive to changes in these components [@bucklandMonitoringChangeBiodiversity2005]. 

Let $n_i$ be the number of individuals of species $i$ and $n = \sum_{i=1}^S n_i$ the total number of individuals of S species in the community, so that $i = 1, \ldots , S$. Evenness measures how uniform the species proportions $p_i$ are, where $p_i = n_i /n$. Now consider surveying a single location and counting the individuals of a group of species over time. The counts $n_{i,j}$ are the number of individuals encountered of species $i$ in year $j$. Because population growth is a multiplicative process, changes in $n_i$ over time are best measured as ratios $n_{i,j+1}/n_{i,j}$. Trends in the abundance of individual species can then be aggregated using the geometric mean [@buckland2011geometric] or equivalently, the arithmetic mean of the changes in log abundances $G_j = exp \left( \frac{1}{S}\sum_{i=1}^S log \frac{n_{i,j+1}}{n_{i,j}}\right)$. The well-known Living Planet Index, for example, is based on the geometric mean [@lohLivingPlanetIndex2005; @mcraeDiversityWeightedLivingPlanet2017].

The LPI is a population trend aggregation method. This means that the global LPI measure reflects an aggregated trend of various vertebrate species on Earth over time [@mcraeDiversityWeightedLivingPlanet2017]. However, biodiversity does not have just one definition, but instead encapsulates a broader concept where there are multiple metrics needed to capture different aspects of biodiversity [@gastonBiodiversityIntroduction2013]. Biodiversity measures are commonly broken up into two basic components. That is, how many different species are present in an ecosystem [@magurranMeasuringBiologicalDiversity2003] and how many individuals per species are present in an ecosystem (evenness) [@bucklandMonitoringChangeBiodiversity2005]. Based on these components of biodiversity, a community with more species tends to have higher biodiversity than a community with fewer species and a community that displays high levels of evenness is regarded more diverse than a community with the same number of species but that displays high levels of unevenness. Regarding the concept of evenness, if two communities have the same number of species, the one where each species is equally abundant (high degree of evenness) is more diverse than one where there are a few common species and the rest are rare (high degree of unevenness). The exponentiated Shannon's index and the Simpson's index are the two most common indices used to measure effective number of species in an ecosystem, and ecosystem evenness, respectively [@hillDiversityEvennessUnifying1973].

The above mentioned indices can be beneficial in monitoring ecosystem health. Studies have shown that monitoring the change in diversity of bird species in wetland ecosystems could potentially be beneficial in determining wetland health [@amatWaterbirdsBioindicatorsEnvironmental2010; @gregoryWildBirdIndicators2010; @sekerciogluIncreasingAwarenessAvian2006]. For example, Birds have been used to indicate the eutrophication levels in wetlands in the Mar Menor lagoon of south-eastern Spain [@amatWaterbirdsBioindicatorsEnvironmental2010]. It was discovered that the Great Crested Grebe abundance increased as the eutrophication levels in the lagoon increased. Another example from Southern Spain shows the use of Red-Knobbed Coot to indicate the siltation rate in the water and soil in wetlands [@amatWaterbirdsBioindicatorsEnvironmental2010]. The Red-Knobbed Coot experienced a stark decline in abundance in the 20th century in Southern Spain. This decrease in abundance is attributed to the increased siltation rates in the water and soil in the wetlands in Southern Spain, caused by invasive agricultural practices.

Birds are valuable members of any ecosystem and their count data follows exactly what is needed for a good bio-indicator as effective bio-indicators are quantitative, easy to collect, simple to interpret, reflect causes of change in an ecosystem and indicate general patterns of taxa in the ecosystem [@sekerciogluIncreasingAwarenessAvian2006; @gregoryUsingBirdsIndicators2003]. In this situation we refer to bio-indicators as species whose fluctuation in abundance closely reflects the state of the ecosystem they find themselves in. The pitfall to using birds as bio-indicators is that the count process is often prone to error, either under counting or over counting [@auger-metheGuideStatespaceModeling2021]. When using erroneous counts to calculate environmental indices we see the errors carrying forward through the calculations, and inevitably, negatively affecting the result [@keryBayesianPopulationAnalysis2011a].

Observation error is a hindrance, but can be accounted for when using the correct model. One such model is state-space models (SSMs). SSMs are hierarchical models that are able to decompose observed time series data into a process variation and an observation error component [@keryBayesianPopulationAnalysis2011a]. When applying a State-space time series model within a bayesian context, one is able to output a posterior distribution of counts for each time period [@auger-metheGuideStatespaceModeling2021]. One can then use these posterior counts to calculate various biodiversity indices such as the LPI, exponentiated Shannon's index and the Simpson's index. An added benefit is that we can produce credible intervals for these index values, a quality that is not commonly incorporated in such calculations.

The aim of this paper is to present a method of calculating and presenting biodiversity indices by first fitting a State-space time series model to the count data and then using the posterior output to calculate the biodiversity index. In this paper the indices calculated are a modified LPI, an exponentiated Shannon's index and a Simpson's index with their respective credible intervals. The data being used for this report is from the Coordinated Waterbird Counts (CWAC) project. CWAC is a citizen scientist initiative that contains water bird counts of over 200 different bird species from approximately 400 different wetland locations in South Africa. Some of these counts go as far back as the 1970s. This report will focus on the bird counts from the Barberspan wetland in North West Province of South Africa. 






