---
title: " "
output: pdf_document
---

# Method

## Study Area

The bird counts used in this study come from the Barberspan wetland which is the pilot site for this study. The Barberspan wetland is situated in North West province, South Africa. It is a protected wetland site known as Barberspan Bird Sanctuary that covers a 3200ha area. The wetland is centered on a shallow lake which covers approximately 257ha to 2000ha depending on rain fall [@remisiewiczStatusMigrantResident2011].

RAMSAR reports that the Barberspan wetland regularly supports approximately 20000 waterbirds with 365 different bird species [@rothmannjBarberspan2015]. Barberspan is one of the first RAMSAR sites in South Africa and the only RAMSAR site in North West province. 

Barberspan wetland is home to thousands of Little Stints and Curlew Sandpipers. It's also a popular location for intra-African nomadic waders such as Kittlitz's Plover and Crowned Lapwing. The bird species with the highest abundance in Barperspan wetland is the Red-Knobbed Coot, Egyptian Goose, Yellow Billed Duck, Southern Pochard and the South African Shelduck [@remisiewiczStatusMigrantResident2011]. Appendix A contains further information regarding the waterbirds found in Barberspan wetland that was used in this study. The Barberspan wetland is rich in bird data and thus is an ideal wetland to use as a pilot site for this study.

## Exploratory Data Analysis
The data used in this paper is from the Coordinated Waterbird Counts (CWAC) initiative. The counts are conducted twice a year, once in January/February (austral
summer) and once in June/July (austral winter). The counting procedure is standardised and follows a rigorous set of instructions that counters are to follow. The counting protocol is such that all counts take place at approximately the same time each day, when the sun is either behind or beside the counter. More details about the counting process can be found at the following link (https://cwac.birdmap.africa/).

The CWAC dataset contains bird counts from 1993 to 2013 for the Barberspan wetland. Missing counts were inserted into the dataset as missing values that will subsequently be predicted by the state-space time series model. Only birds with 15 or more non-zero counts were used in the analysis as the variance parameters for the state-space time series model didn't converge when applied to bird counts with fewer than 15 non-zero counts.

## State-Space Time Series Model

A state-space time series model (SSM) was fitted to the bird count data. State-space models have become increasingly popular tools in modelling population dynamics [@auger-metheGuideStatespaceModeling2021]. The key benefit of a state-space model is its ability to separate observation error and latent error. By removing the observation error from the latent error, one is able to predict population trends more accurately [@keryBayesianPopulationAnalysis2011a]. SSMs are an ideal tool to use for time series analysis for the CWAC dataset, as bird counts are often prone to high levels of observation error and follow a markovian process, where the value at time t is dependent on the value at time t-1 (see figure x for illustration of markovian chain).

In this study the CWAC bird counts are modeled using an existing state-space time series model that was created by @barshepIdentifyingEcologicalLifehistory2017 and applied to bird count data in the CWAC dataset. @barshepIdentifyingEcologicalLifehistory2017 developed a bivariate time series model that treats summer and winter counts as separate variables, with the focus being on the summer population. The winter counts are modeled as a proportion of the summer counts as some birds from Barberspan migrate north during the southern winter.

SSMs model the state process and observation process separately such that state error and observation error can be separated for more accurate modelling of the count data. The mathematical illustration of the bivariate model is displayed below:

_observation process_

\begin{equation}
  ln(summer\;count): s_{t} = \mu_{t-1} + \alpha_{t},\;\;\;\alpha_{t} \sim N(0,\sigma^{2}_\alpha)
\end{equation}

\begin{equation}
  ln(winter\;count): w_{t} = \mu_{t} + \lambda_{t} + e_{t},\;\;\;e_{t} \sim N(0,\sigma^{2}_e)
\end{equation}

_state process_

\begin{equation}
  ln(summer\;population\;level): \mu_{t} = \mu_{t-1} + \beta_{t-1} + w_{t}, \;\;\; w_{t} \sim N(0, \sigma^{2}_w)
\end{equation}

\begin{equation}
  ln(population\;change): \beta_{t} = \beta_{t-1} + \zeta_{t}, \;\;\; \zeta_{t} \sim N(0, \sigma^{2}_\zeta)
\end{equation}

\begin{equation}
  ln(summer\;to\;winter\;ratio): \lambda_{t} = \lambda_{t-1} + \epsilon_{t}, \;\;\; \epsilon_{t} \sim N(0,\sigma^{2}_\epsilon)
\end{equation}

where, $s_{t}$ is the summer count at time $t$ and $w_{t}$ is the winter count at time $t$. $\mu_{t}$ is the latent summer population, $\beta_{t}$ is the rate of change at time $t$ and $\lambda$ is the winter to summer ratio. The winter to summer ratio refers to the difference in the bird population from summer to winter. The palearctic migrants usually migrate north for winter, and leave their young behind, thus leaving a smaller proportion of birds in the South African wetlands in winter compared to summer.  $\alpha_{t}$, $e_{t}$, $w_{t}$, $\zeta_{t}$ and $\epsilon_{t}$ are all normally distributed, serially independent and independent of each other with variance $\sigma^{2}_\alpha$, $\sigma^{2}_e$, $\sigma^{2}_w$, $\sigma^{2}_\zeta$ and $\sigma^{2}_\epsilon$ respectively.


- briefly explain gibbs sampler (an MCMC algorithm)
The time series model presented above follows a Markovian process as the value of time t is dependent on the value at time t-1. The aim of this analysis is to sample from the probability distributions that represent the summer and winter counts. The current distribution for these summer and winter counts are unknown, but by applying Monte Carlo simulations from the summer and winter count distributions we can generate values that are from an approximation of the true count distribution (the stationery distribution). This process is known as a Monte Carlo Markov Chain (MCMC) approach. The simulated values are known as the posterior distribution and is later used to calculate bio indices with credible intervals.

First value of the chain is defined by a distribution (in our case it was a random value I think)
In this analysis the MCMC algorithm used is the Gibbs Sampler, which is applied using the JAGS package in R [@plummerJAGSProgramAnalysis2003; @R; @jagsui]. The JAGS software implements Bayesian inference based on Gibbs sampling by using a MCMC approach [@coroGibbsSamplingJAGS2017]. The hyperparameters available in the JAGS program are number of chains (n.chains), number of iterations (n.iter) and burn-in length (n.burnin). The number of chains refers to the number of markov chains created. These are the number of chains that run in parallel to generate samples from the stationery distribution. A trace plot can also be plotted to show if these chains converge or not for a given count value. If all chains converge around the same approximation then we can be satisfied that the model has reached convergence. The number of chains was set to three in this analysis. The hyperparameters for number of iterations and "burn-in" for the Gibbs Sampler was 10 000 and 5000 respectively. The number of iterations refers to the number of times the Gibbs Sampler samples from the stationery distribution that represents the summer or winter counts. The "burn-in" hyperparameter refers to the first few iterations that are to be discarded given that these first few iterations are usually less probable outcomes, but as the model runs for a longer period of iterations, the outcomes tend toward a higher probability region and thus are more likely outcomes. This generates an output of 15 000 count values for each bird for each year with the first 5000 iterations being the "burn-in" iterations.

## Biodiversity indices
- Speak about the modified LPI

The 10 000 approximated count values for each bird count per year was used in calculating the modified LPI, exponentiated Shannon index and the Simpson index. The benefit of using the whole posterior sample of bird counts is so that a credible interval could be calculated for each index.

### Abundance Index

A popular population abundance index is the Living Planet Index (LPI) that is designed to track
changes in population sizes over time. The LPI is used as an aggregated abundance index. It
calculates the percentage change from a reference year (1970) to all subsequent years. This is done by
averaging the rate of change (from reference year to current year) across all species of a species group
(McRae, Deinet, and Freeman 2017). PARAPHRASE THIS

A modified LPI approach was used to form an abundance index in this study. The modified LPI used
calculates percentage change from each year to the next for a trait specific group of waterbirds.
The modified LPI calculations were applied to the mean summer population posterior value, per
year, estimated by the state-space model. The SSM was first applied to each species in a trait
specific group separately. The percentage change for each year was calculated for each species, then
the average percentage change across all species in the group was calculated, per year. The
calculations used are as follows PARAPHRASE THIS __ also add what makes the modified approach different to normal LPI approach

- Speak about the exponential Shannon index and Simpsons index (first try using the shannon equitability index)



